### ISSUE TITLE
GitHub Actions Warning

### ISSUE THREAD

**Issue by mitrejcevski** [chkfung/android-version-actions#7]
GitHub gives warning for the current version of the action (v1.1)

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: chkfung/android-version-actions

**Comment by chkfung** [comment]
updated node environment on 1.2
